import type { Locale } from "./i18n";

export type Category = "beans" | "ground" | "capsules" | "pods" | "accessories";

// Vergnano product lines shown as the main navigation of the catalog.
export type Collection =
  | "riserva-torino"
  | "line-1882"
  | "classic-line"
  | "beans"
  | "single-origin"
  | "pink-collection"
  | "ground";

export const collections: Collection[] = [
  "riserva-torino",
  "line-1882",
  "classic-line",
  "beans",
  "single-origin",
  "pink-collection",
  "ground",
];

export const collectionImages: Record<Collection | "all", string> = {
  "riserva-torino": "/images/riserva/riserva-torino-hero.jpg",
  "line-1882": "/images/lines/1882-line/linea-1882.jpg",
  "classic-line": "/images/lines/classic-line/linea-classica.jpg",
  beans: "/images/categories/caffe-grani.jpg",
  "single-origin": "/images/lines/single-origin/hero-so.jpg",
  "pink-collection": "/images/categories/pink-collection.jpg",
  ground: "/images/categories/caffe-macinato.jpg",
  all: "/images/categories/moka-e-tazzine.jpg",
};

export interface Product {
  id: string;
  name: string;
  category: Category; // product form — drives detail-page facts
  collection: Collection | null; // catalog line; null = shown under "All" only
  packSize: string;
  intensity: number | null;
  // Retail price in UZS. Placeholder values — edit freely; the rest of the
  // site (cards, cart, Telegram order message) picks them up automatically.
  price: number;
  image: string;
  description: Record<Locale, string>;
}

export const products: Product[] = [
  {
    id: "beans-antica-bottega",
    name: "Antica Bottega",
    category: "beans",
    collection: "beans",
    packSize: "1 kg",
    intensity: 5,
    price: 420000,
    image: "/products/beans-antica-bottega.png",
    description: {
      uz: "Shirin va nozik aralashma — yengil nordonlik, to'liq tana va mayin, uzoq davom etuvchi krema. Har bir nav an'anaviy usulda alohida sekin qovuriladi.",
      ru: "Сладкая, деликатная смесь — лёгкая кислинка, полное тело и тонкая стойкая крема. Каждый сорт обжаривается отдельно по традиционной технологии.",
      en: "A sweet, delicate blend with light acidity, full body and a fine, persistent crema. Each origin is slow-roasted separately in the traditional style.",
    },
  },
  {
    id: "beans-espresso",
    name: "Espresso",
    category: "beans",
    collection: "beans",
    packSize: "1 kg",
    intensity: 7,
    price: 340000,
    image: "/products/beans-espresso.png",
    description: {
      uz: "To'liq tanali, xushbo'y espresso aralashmasi — shirin, mevali ta'm va jozibali krema. Arabica va Robusta mukammal uyg'unlikda.",
      ru: "Полнотелая ароматная эспрессо-смесь — сладкий фруктовый вкус и аппетитная крема. Арабика и робуста в идеальной гармонии.",
      en: "A full-bodied, fragrant espresso blend with a sweet, fruity taste and an inviting crema. Arabica and Robusta in perfect harmony.",
    },
  },
  {
    id: "beans-granaroma",
    name: "Granaroma",
    category: "beans",
    collection: "beans",
    packSize: "1 kg",
    intensity: 8,
    price: 350000,
    image: "/products/beans-granaroma.png",
    description: {
      uz: "Shokoladli, kuchli klassik aralashma — boy va barqaror ta'm. Har kun uchun ideal tanlov.",
      ru: "Шоколадная, интенсивная классическая смесь — богатый, устойчивый вкус. Идеальный выбор на каждый день.",
      en: "A chocolate-forward, intense classic blend with a rich, persistent taste. The perfect everyday choice.",
    },
  },
  {
    id: "beans-arabica",
    name: "100% Arabica",
    category: "beans",
    collection: "beans",
    packSize: "250 g",
    intensity: 4,
    price: 120000,
    image: "/products/beans-arabica.png",
    description: {
      uz: "Nozik va xushbo'y 100% Arabica — yengil tanali, ammo to'liq aromatli. Yumshoq qahvani sevuvchilar uchun.",
      ru: "Деликатная ароматная 100% арабика — лёгкое тело, но насыщенный аромат. Для тех, кто любит мягкий кофе.",
      en: "A delicate, aromatic 100% Arabica — light in body yet fragrant and full. For those who prefer a gentler cup.",
    },
  },
  {
    id: "ground-granaroma",
    name: "Granaroma Macinato",
    category: "ground",
    collection: "ground",
    packSize: "250 g",
    intensity: 7,
    price: 95000,
    image: "/products/ground-granaroma.png",
    description: {
      uz: "Klassik Granaroma aralashmasi moka uchun maydalangan — boy ta'm va o'ziga xos aromat.",
      ru: "Классическая смесь Granaroma, смолотая для гейзерной кофеварки — богатый вкус и характерный аромат.",
      en: "The classic Granaroma blend ground for the moka pot — rich flavour and a distinctive aroma.",
    },
  },
  {
    id: "ground-antica-bottega",
    name: "Antica Bottega Macinato",
    category: "ground",
    collection: "ground",
    packSize: "250 g",
    intensity: 4,
    price: 110000,
    image: "/products/ground-antica-bottega.png",
    description: {
      uz: "Markaziy Amerika Arabikasi va Robusta aralashmasi, moka uchun. Sekin qovurish unga yumshoq, nozik ta'm beradi.",
      ru: "Смесь центральноамериканской арабики и робусты для моки. Медленная обжарка придаёт мягкий, деликатный вкус.",
      en: "Central American Arabica blended with Robusta, ground for moka. Slow roasting gives a smooth, delicate flavour.",
    },
  },
  {
    id: "ground-espressocasa",
    name: "Espressocasa",
    category: "ground",
    collection: "ground",
    packSize: "250 g",
    intensity: 8,
    price: 105000,
    image: "/products/ground-espressocasa.png",
    description: {
      uz: "Uy espresso mashinalari uchun kremali, ziravorli mayda maydalangan qahva — uyda bar sifatidagi espresso.",
      ru: "Кремовый, пряный тонкий помол для домашних эспрессо-машин — эспрессо барного качества у вас дома.",
      en: "A creamy, spiced fine grind for home espresso machines — bar-quality espresso at home.",
    },
  },
  {
    id: "ground-arabica-tin",
    name: "100% Arabica Lattina",
    category: "ground",
    collection: "ground",
    packSize: "250 g tin",
    intensity: 7,
    price: 150000,
    image: "/products/ground-arabica-tin.png",
    description: {
      uz: "Mashhur Vergnano bankasidagi premium Arabica, espresso uchun maydalangan. Muvozanatli, mevali va yumaloq aromat.",
      ru: "Премиальная арабика в легендарной банке Vergnano, помол для эспрессо. Сбалансированный, фруктовый, округлый вкус.",
      en: "Premium Arabica in the iconic Vergnano tin, ground for espresso. Balanced and fruity with a rounded aroma.",
    },
  },
  {
    id: "caps-cremoso",
    name: "Cremoso",
    category: "capsules",
    collection: null,
    packSize: "30 capsules · Nespresso®*",
    intensity: 6,
    price: 195000,
    image: "/products/caps-cremoso.png",
    description: {
      uz: "Yong'oq va kakao notalari bilan mayin, barqaror aralashma — boy, baxmal espresso. Kompostlanadigan kapsulalar.",
      ru: "Мягкая, стойкая смесь с ореховыми и какао-нотами — насыщенный бархатный эспрессо. Компостируемые капсулы.",
      en: "A soft, persistent blend with nutty aromas and cocoa notes — a rich, velvety espresso. Compostable capsules.",
    },
  },
  {
    id: "caps-intenso",
    name: "Intenso Èspresso 1882",
    category: "capsules",
    collection: null,
    packSize: "30 capsules · Nespresso®*",
    intensity: 8,
    price: 195000,
    image: "/products/caps-intenso.png",
    description: {
      uz: "Qat'iy va to'liq tanali — shokolad va ziravor notalari Amerika Arabikasi bilan yumshatilgan. Kompostlanadigan kapsulalar.",
      ru: "Решительный и полнотелый — шоколадные и пряные ноты, смягчённые американской арабикой. Компостируемые капсулы.",
      en: "Decisive and full-bodied, with chocolatey, spicy notes softened by smooth American Arabica. Compostable capsules.",
    },
  },
  {
    id: "caps-arabica",
    name: "100% Arabica Capsule",
    category: "capsules",
    collection: null,
    packSize: "30 capsules · Nespresso®*",
    intensity: 4,
    price: 195000,
    image: "/products/caps-arabica.png",
    description: {
      uz: "Nozik va muvozanatli — sariq meva, vanil, karamel va sut shokoladi notalari. Kompostlanadigan kapsulalar.",
      ru: "Деликатный и сбалансированный — ноты жёлтых фруктов, ванили, карамели и молочного шоколада. Компостируемые капсулы.",
      en: "Delicate and balanced — notes of yellow fruit, vanilla, caramel and milk chocolate. Compostable capsules.",
    },
  },
  {
    id: "caps-decaf",
    name: "Decaffeinato",
    category: "capsules",
    collection: null,
    packSize: "30 capsules · Nespresso®*",
    intensity: 5,
    price: 195000,
    image: "/products/caps-decaf.png",
    description: {
      uz: "Nafis kofeinsiz qahva — sitrus, qizil meva, choy va sut shokoladi notalari. Kompostlanadigan kapsulalar.",
      ru: "Элегантный декаф — ноты цитрусов, красных ягод, чая и молочного шоколада. Компостируемые капсулы.",
      en: "An elegant decaf with bright notes of citrus, red fruits, tea and milk chocolate. Compostable capsules.",
    },
  },
  {
    id: "caps-oro-50",
    name: "Oro",
    category: "capsules",
    collection: null,
    packSize: "50 capsules · Nespresso®*",
    intensity: 4,
    price: 280000,
    image: "/products/caps-oro-50.png",
    description: {
      uz: "Nozik, muvozanatli aralashma — meva va vanil notalari, karamel shirinligi. Tejamkor 50 talik quti.",
      ru: "Деликатная сбалансированная смесь — фруктово-ванильные ноты со сладостью карамели. Выгодная упаковка из 50 капсул.",
      en: "A delicate, balanced blend with fruit and vanilla notes plus caramel sweetness. Value 50-pack.",
    },
  },
  {
    id: "pods-espresso-150",
    name: "Espresso Cialde",
    category: "pods",
    collection: null,
    packSize: "150 ESE pods",
    intensity: 7,
    price: 590000,
    image: "/products/pods-espresso-150.png",
    description: {
      uz: "Boy va kremali ESE qog'oz chaldalar — to'liq ta'm, kuchli aromat va quyuq krema. Kompostlanadigan.",
      ru: "Насыщенные кремовые чалды ESE — полный вкус, интенсивный аромат и плотная крема. Компостируемые.",
      en: "Rich, creamy ESE paper pods — full-bodied taste, intense aroma and a dense crema. Compostable.",
    },
  },
  {
    id: "pods-oro-150",
    name: "Oro Cialde",
    category: "pods",
    collection: null,
    packSize: "150 ESE pods",
    intensity: 5,
    price: 590000,
    image: "/products/pods-oro-150.png",
    description: {
      uz: "Nozik va muvozanatli ESE chaldalar — yumshoq, to'liq ta'm va yorqin aromat. Kompostlanadigan.",
      ru: "Деликатные сбалансированные чалды ESE — мягкий полный вкус и выраженный аромат. Компостируемые.",
      en: "Delicate, balanced ESE pods with a smooth, full taste and pronounced fragrance. Compostable.",
    },
  },
  {
    id: "acc-moka-nera",
    name: "Moka Nera",
    category: "accessories",
    collection: null,
    packSize: "3 cups",
    intensity: null,
    price: 450000,
    image: "/products/acc-moka-nera.png",
    description: {
      uz: "Vergnano brendidagi matoviy qora moka — uyda qahva tayyorlashning klassik italyan usuli.",
      ru: "Гейзерная кофеварка Vergnano в матовом чёрном цвете — классический итальянский способ варить кофе дома.",
      en: "A Vergnano-branded matte black stovetop moka pot — the classic Italian way to brew at home.",
    },
  },
  {
    id: "acc-tazzine-rosse",
    name: "Set da 6 Tazzine Rosse",
    category: "accessories",
    collection: null,
    packSize: "6 cups + saucers",
    intensity: null,
    price: 650000,
    image: "/products/acc-tazzine-rosse.png",
    description: {
      uz: "Olti dona qizil Caffè Vergnano espresso finjonlari — uyingizda haqiqiy 1882 bar uslubi.",
      ru: "Набор из шести красных эспрессо-чашек Caffè Vergnano — фирменный стиль бара 1882 у вас дома.",
      en: "Set of six red Caffè Vergnano espresso cups with saucers — the signature 1882 bar look at home.",
    },
  },

  // ---- Vergnano lines & shop range (images from caffevergnano.com) ----
  {
    id: "rt-nobile",
    name: "Riserva Torino Nobile",
    category: "beans",
    collection: "riserva-torino",
    packSize: "1 kg",
    intensity: 8,
    price: 520000,
    image: "/images/riserva/riserva-torino-nobile.png",
    description: {
      uz: "Eng yaxshi Arabica va Robusta navlarining mohirona muvozanati — boy va kuchli ta'm.",
      ru: "Искусный баланс лучших сортов арабики и робусты — насыщенный и интенсивный вкус.",
      en: "A skilful balance of the finest Arabica and Robusta origins — rich and intense.",
    },
  },
  {
    id: "rt-arabica",
    name: "Riserva Torino 100% Arabica",
    category: "beans",
    collection: "riserva-torino",
    packSize: "1 kg",
    intensity: 6,
    price: 560000,
    image: "/images/riserva/arabica-rt-1.png",
    description: {
      uz: "Karamel notalari bilan nozik — sut shokoladi, yong'oq va qizilmiya nozikliklari bilan ajoyib espresso.",
      ru: "Деликатный, с нотами карамели — превосходный эспрессо с оттенками молочного шоколада, орехов и лакрицы.",
      en: "Delicate, with notes of caramel — an extraordinary espresso with hints of milk chocolate, nuts and liquorice.",
    },
  },
  {
    id: "rt-cremoso",
    name: "Riserva Torino Cremoso",
    category: "beans",
    collection: "riserva-torino",
    packSize: "1 kg",
    intensity: 9,
    price: 520000,
    image: "/images/riserva/cremoso-rt-1.png",
    description: {
      uz: "Boy va barqaror — kakao, ziravorlar va yong'oq notalari.",
      ru: "Насыщенный и стойкий — ноты какао, специй и орехов.",
      en: "Rich and persistent — hints of cocoa, spices and nuts.",
    },
  },
  {
    id: "rt-caps-nobile",
    name: "Riserva Torino Nobile — Capsule",
    category: "capsules",
    collection: "riserva-torino",
    packSize: "10 capsules · Nespresso®*",
    intensity: 8,
    price: 95000,
    image: "/images/riserva/capsules.png",
    description: {
      uz: "Riserva Torino Nobile aralashmasi Nespresso®* uchun mos kapsulalarda.",
      ru: "Смесь Riserva Torino Nobile в капсулах, совместимых с Nespresso®*.",
      en: "The Riserva Torino Nobile blend in Nespresso®*-compatible capsules.",
    },
  },
  {
    id: "rt-caps-arabica",
    name: "Riserva Torino 100% Arabica — Capsule",
    category: "capsules",
    collection: "riserva-torino",
    packSize: "10 capsules · Nespresso®*",
    intensity: 6,
    price: 95000,
    image: "/images/riserva/capsules.png",
    description: {
      uz: "Riserva Torino 100% Arabica aralashmasi Nespresso®* uchun mos kapsulalarda.",
      ru: "Смесь Riserva Torino 100% Arabica в капсулах, совместимых с Nespresso®*.",
      en: "The Riserva Torino 100% Arabica blend in Nespresso®*-compatible capsules.",
    },
  },
  {
    id: "rt-caps-cremoso",
    name: "Riserva Torino Cremoso — Capsule",
    category: "capsules",
    collection: "riserva-torino",
    packSize: "10 capsules · Nespresso®*",
    intensity: 9,
    price: 95000,
    image: "/images/riserva/capsules.png",
    description: {
      uz: "Riserva Torino Cremoso aralashmasi Nespresso®* uchun mos kapsulalarda.",
      ru: "Смесь Riserva Torino Cremoso в капсулах, совместимых с Nespresso®*.",
      en: "The Riserva Torino Cremoso blend in Nespresso®*-compatible capsules.",
    },
  },
  {
    id: "l1882-original",
    name: "1882 Original",
    category: "beans",
    collection: "line-1882",
    packSize: "2,5 kg",
    intensity: 7,
    price: 950000,
    image: "/images/lines/1882-line/linea-1882-original.png",
    description: {
      uz: "O'rtacha qovurish — meva va asal notalari bilan nozik, xushbo'y aralashma; shokolad nozikliklari va quyuq krema.",
      ru: "Средняя обжарка — деликатная ароматная смесь с нотами фруктов и мёда; шоколадные нюансы и плотная крема.",
      en: "Medium roast — a delicate, aromatic blend with hints of fruit and honey; chocolate notes and a dense crema.",
    },
  },
  {
    id: "l1882-strong",
    name: "1882 Strong",
    category: "beans",
    collection: "line-1882",
    packSize: "2,5 kg",
    intensity: 9,
    price: 950000,
    image: "/images/lines/1882-line/linea-1882-strong.png",
    description: {
      uz: "Kuchli va to'yingan — Janubiy Amerika va Osiyo Robustalarining quyuq, uzoq davom etuvchi ta'mi.",
      ru: "Крепкий и насыщенный — плотный, стойкий вкус робусты Южной Америки и Азии.",
      en: "Strong and full-bodied — a dense, long-lasting taste from South American and Asian Robustas.",
    },
  },
  {
    id: "l1882-very-strong",
    name: "1882 Very Strong",
    category: "beans",
    collection: "line-1882",
    packSize: "2,5 kg",
    intensity: 10,
    price: 950000,
    image: "/images/lines/1882-line/linea-1882-very-strong.png",
    description: {
      uz: "Eng kuchli 1882 aralashmasi — juda intensiv, kuchli tanali espresso.",
      ru: "Самая крепкая смесь 1882 — очень интенсивный, полнотелый эспрессо.",
      en: "The strongest 1882 blend — a very intense, full-bodied espresso.",
    },
  },
  {
    id: "l1882-arabica",
    name: "1882 100% Arabica",
    category: "beans",
    collection: "line-1882",
    packSize: "2,5 kg",
    intensity: 6,
    price: 1050000,
    image: "/images/lines/1882-line/linea-1882-100-arabica.png",
    description: {
      uz: "100% Arabica — muvozanatli, xushbo'y va yumshoq, bar uchun ideal.",
      ru: "100% арабика — сбалансированный, ароматный и мягкий, идеален для бара.",
      en: "100% Arabica — balanced, aromatic and smooth, ideal for the bar.",
    },
  },
  {
    id: "cl-1000",
    name: "1000 Mille — Extra Dolce",
    category: "beans",
    collection: "classic-line",
    packSize: "1 kg",
    intensity: 5,
    price: 430000,
    image: "/images/lines/classic-line/linea-classica-100.jpg",
    description: {
      uz: "Juda shirin espresso — eng yumshoq Classic Line aralashmasi.",
      ru: "Экстра-сладкий эспрессо — самая мягкая смесь Classic Line.",
      en: "Extra-sweet espresso — the smoothest blend in the Classic Line.",
    },
  },
  {
    id: "cl-900",
    name: "900 Novecento — Dolce",
    category: "beans",
    collection: "classic-line",
    packSize: "1 kg",
    intensity: 6,
    price: 410000,
    image: "/images/lines/classic-line/linea-classica-900.jpg",
    description: {
      uz: "Shirin espresso — 90% Arabica, muvozanatli va xushbo'y.",
      ru: "Сладкий эспрессо — 90% арабики, сбалансированный и ароматный.",
      en: "Sweet espresso — 90% Arabica, balanced and aromatic.",
    },
  },
  {
    id: "cl-800",
    name: "800 Ottocento — Crema",
    category: "beans",
    collection: "classic-line",
    packSize: "1 kg",
    intensity: 7,
    price: 390000,
    image: "/images/lines/classic-line/linea-classica-800.jpg",
    description: {
      uz: "Boy krema — 80% Arabica, to'liq va yumaloq ta'm.",
      ru: "Плотная крема — 80% арабики, полный и округлый вкус.",
      en: "Rich crema — 80% Arabica, full and rounded.",
    },
  },
  {
    id: "cl-700",
    name: "700 Settecento — Ricco",
    category: "beans",
    collection: "classic-line",
    packSize: "1 kg",
    intensity: 8,
    price: 370000,
    image: "/images/lines/classic-line/linea-classica-700.jpg",
    description: {
      uz: "Boy va kuchli — 70% Arabica, 30% Robusta.",
      ru: "Насыщенный и интенсивный — 70% арабики, 30% робусты.",
      en: "Rich and intense — 70% Arabica, 30% Robusta.",
    },
  },
  {
    id: "cl-600",
    name: "600 Seicento — Classico",
    category: "beans",
    collection: "classic-line",
    packSize: "1 kg",
    intensity: 9,
    price: 350000,
    image: "/images/lines/classic-line/linea-classica-600.jpg",
    description: {
      uz: "Klassik italyan espressosi — 60% Arabica, kuchli tana.",
      ru: "Классический итальянский эспрессо — 60% арабики, плотное тело.",
      en: "Classic Italian espresso — 60% Arabica, strong body.",
    },
  },
  {
    id: "cl-500",
    name: "500 Cinquecento — Intenso",
    category: "beans",
    collection: "classic-line",
    packSize: "1 kg",
    intensity: 10,
    price: 340000,
    image: "/images/lines/classic-line/linea-classica-500.jpg",
    description: {
      uz: "Eng intensiv Classic Line aralashmasi — 50% Arabica, 50% Robusta.",
      ru: "Самая интенсивная смесь Classic Line — 50% арабики, 50% робусты.",
      en: "The most intense Classic Line blend — 50% Arabica, 50% Robusta.",
    },
  },
  {
    id: "cl-arabica-bio",
    name: "Arabica Bio",
    category: "beans",
    collection: "classic-line",
    packSize: "1 kg",
    intensity: 6,
    price: 450000,
    image: "/images/lines/classic-line/linea-classica-arabica-bio.jpg",
    description: {
      uz: "Sertifikatlangan organik 100% Arabica.",
      ru: "Сертифицированная органическая 100% арабика.",
      en: "Certified organic 100% Arabica.",
    },
  },
  {
    id: "cl-decaf",
    name: "Decaffeinato",
    category: "beans",
    collection: "classic-line",
    packSize: "1 kg",
    intensity: 5,
    price: 420000,
    image: "/images/lines/classic-line/linea-classica-decaffeinato.jpg",
    description: {
      uz: "Kofeinsiz — ta'mi to'liq saqlangan.",
      ru: "Без кофеина — с полностью сохранённым вкусом.",
      en: "Decaffeinated — with the flavour fully preserved.",
    },
  },
  {
    id: "so-brazil",
    name: "Single Origin Brazil",
    category: "beans",
    collection: "single-origin",
    packSize: "1 kg",
    intensity: 6,
    price: 480000,
    image: "/images/lines/single-origin/brazil.png",
    description: {
      uz: "Braziliya — kakao, quruq mevalar va don notalari bilan yumshoq va muvozanatli.",
      ru: "Бразилия — мягкий и сбалансированный, с нотами какао, сухофруктов и злаков.",
      en: "Brazil — smooth and balanced, with notes of cocoa, dried fruit and cereals.",
    },
  },
  {
    id: "so-colombia",
    name: "Single Origin Colombia",
    category: "beans",
    collection: "single-origin",
    packSize: "1 kg",
    intensity: 7,
    price: 490000,
    image: "/images/lines/single-origin/colombia.png",
    description: {
      uz: "Kolumbiya — qizil mevalar va shokolad notalari bilan yorqin, boy ta'm.",
      ru: "Колумбия — яркий насыщенный вкус с нотами красных ягод и шоколада.",
      en: "Colombia — bright and rich, with notes of red fruits and chocolate.",
    },
  },
  {
    id: "so-honduras",
    name: "Single Origin Honduras",
    category: "beans",
    collection: "single-origin",
    packSize: "1 kg",
    intensity: 6,
    price: 480000,
    image: "/images/lines/single-origin/honduras.png",
    description: {
      uz: "Gonduras — bodom va qandolat notalari bilan shirin va nozik.",
      ru: "Гондурас — сладкий и деликатный, с нотами миндаля и выпечки.",
      en: "Honduras — sweet and delicate, with notes of almond and pastry.",
    },
  },
  {
    id: "beans-antica-bottega-500",
    name: "Antica Bottega",
    category: "beans",
    collection: "beans",
    packSize: "500 g",
    intensity: 5,
    price: 230000,
    image: "/products/shop/caffe-grani__anticabottega-500g.png",
    description: {
      uz: "Shirin va nozik aralashma — 500 g qadoqda.",
      ru: "Сладкая деликатная смесь — упаковка 500 г.",
      en: "The sweet, delicate blend — 500 g pack.",
    },
  },
  {
    id: "beans-espresso-500",
    name: "Espresso",
    category: "beans",
    collection: "beans",
    packSize: "500 g",
    intensity: 7,
    price: 190000,
    image: "/products/shop/caffe-grani__espresso-500g.png",
    description: {
      uz: "To'liq tanali espresso aralashmasi — 500 g.",
      ru: "Полнотелая эспрессо-смесь — 500 г.",
      en: "Full-bodied espresso blend — 500 g.",
    },
  },
  {
    id: "beans-granaroma-500",
    name: "Granaroma",
    category: "beans",
    collection: "beans",
    packSize: "500 g",
    intensity: 8,
    price: 195000,
    image: "/products/shop/caffe-grani__granaroma-500g.png",
    description: {
      uz: "Shokoladli klassik aralashma — 500 g.",
      ru: "Шоколадная классическая смесь — 500 г.",
      en: "The chocolaty classic blend — 500 g.",
    },
  },
  {
    id: "beans-arabica-bio",
    name: "Arabica Bio",
    category: "beans",
    collection: "beans",
    packSize: "1 kg",
    intensity: 6,
    price: 460000,
    image: "/products/shop/caffe-grani__sacco-bio-1kg.png",
    description: {
      uz: "Organik sertifikatli 100% Arabica donalari.",
      ru: "Органическая 100% арабика в зёрнах.",
      en: "Certified organic 100% Arabica beans.",
    },
  },
  {
    id: "beans-wic-honduras",
    name: "Women in Coffee — Honduras Blend",
    category: "beans",
    collection: "beans",
    packSize: "250 g",
    intensity: 6,
    price: 140000,
    image: "/products/shop/caffe-grani__grani-wic-honduras-blend-250g.png",
    description: {
      uz: "Women in Coffee loyihasi — Gonduras ayol fermerlari yetishtirgan qahva.",
      ru: "Проект Women in Coffee — кофе, выращенный женщинами-фермерами Гондураса.",
      en: "Women in Coffee project — coffee grown by women farmers in Honduras.",
    },
  },
  {
    id: "ground-arabica-tin-moka",
    name: "100% Arabica Lattina (Moka)",
    category: "ground",
    collection: "ground",
    packSize: "250 g tin",
    intensity: 6,
    price: 150000,
    image: "/products/shop/caffe-macinato__lattina-caffe-macinato-100-arabica-250g.png",
    description: {
      uz: "Moka uchun maydalangan 100% Arabica — afsonaviy bankada.",
      ru: "100% арабика помола для моки — в легендарной банке.",
      en: "100% Arabica ground for moka — in the iconic tin.",
    },
  },
  {
    id: "ground-decaf-tin",
    name: "Decaffeinato Lattina",
    category: "ground",
    collection: "ground",
    packSize: "250 g tin",
    intensity: 5,
    price: 150000,
    image: "/products/shop/caffe-macinato__lattina-decaffeinato-250g.png",
    description: {
      uz: "Kofeinsiz, moka uchun maydalangan — bankada.",
      ru: "Декаф помола для моки — в банке.",
      en: "Decaf ground for moka — in the tin.",
    },
  },
  {
    id: "ground-montagna-tin",
    name: "Montagna 100% Arabica Lattina",
    category: "ground",
    collection: "ground",
    packSize: "250 g tin",
    intensity: 6,
    price: 160000,
    image: "/products/shop/caffe-macinato__lattina-montagna-100-arabica.png",
    description: {
      uz: "Baland tog' plantatsiyalaridan 100% Arabica.",
      ru: "100% арабика с высокогорных плантаций.",
      en: "100% Arabica from high-mountain plantations.",
    },
  },
  {
    id: "ground-granaroma-500",
    name: "Granaroma Macinato",
    category: "ground",
    collection: "ground",
    packSize: "2 × 250 g",
    intensity: 7,
    price: 180000,
    image: "/products/shop/caffe-macinato__caffe-macinato-gran-aroma-2x250g.png",
    description: {
      uz: "Granaroma moka uchun — 2 × 250 g.",
      ru: "Granaroma для моки — 2 × 250 г.",
      en: "Granaroma for moka — 2 × 250 g.",
    },
  },
  {
    id: "ground-granaroma-1kg",
    name: "Granaroma Macinato",
    category: "ground",
    collection: "ground",
    packSize: "4 × 250 g",
    intensity: 7,
    price: 340000,
    image: "/products/shop/caffe-macinato__caffe-macinato-gran-aroma-4x250g.png",
    description: {
      uz: "Granaroma moka uchun — 4 × 250 g tejamkor to'plam.",
      ru: "Granaroma для моки — выгодный набор 4 × 250 г.",
      en: "Granaroma for moka — value pack of 4 × 250 g.",
    },
  },
  {
    id: "ground-antica-bottega-500",
    name: "Antica Bottega Macinato",
    category: "ground",
    collection: "ground",
    packSize: "2 × 250 g",
    intensity: 4,
    price: 210000,
    image: "/products/shop/caffe-macinato__caffe-macinato-antica-bottega-2x250g.png",
    description: {
      uz: "Yumshoq Antica Bottega moka uchun — 2 × 250 g.",
      ru: "Мягкая Antica Bottega для моки — 2 × 250 г.",
      en: "Smooth Antica Bottega for moka — 2 × 250 g.",
    },
  },
  {
    id: "ground-vergnano-ce",
    name: "Vergnano C'è",
    category: "ground",
    collection: "ground",
    packSize: "250 g",
    intensity: 7,
    price: 95000,
    image: "/products/shop/caffe-macinato__vergnano-ce-250g.png",
    description: {
      uz: "Kundalik moka uchun klassik aralashma.",
      ru: "Классическая смесь для ежедневной моки.",
      en: "The classic everyday moka blend.",
    },
  },
  {
    id: "ground-wic-tin",
    name: "Women in Coffee Lattina",
    category: "ground",
    collection: "ground",
    packSize: "250 g tin",
    intensity: 6,
    price: 160000,
    image: "/products/shop/caffe-macinato__lattina-wic-250g.png",
    description: {
      uz: "Women in Coffee — bankada maydalangan qahva.",
      ru: "Women in Coffee — молотый кофе в банке.",
      en: "Women in Coffee — ground coffee in the tin.",
    },
  },
  {
    id: "pink-tin-bianca",
    name: "Lattina Women in Coffee — Pennika Bianca",
    category: "ground",
    collection: "pink-collection",
    packSize: "250 g tin",
    intensity: 6,
    price: 180000,
    image: "/products/shop/pink-collection__lattina-wic-pennika-bianca.png",
    description: {
      uz: "Rassom Pennika dizaynidagi oq banka — Women in Coffee qahvasi.",
      ru: "Белая банка с дизайном художницы Pennika — кофе Women in Coffee.",
      en: "White tin with artwork by Pennika — Women in Coffee coffee.",
    },
  },
  {
    id: "pink-tin-rosa",
    name: "Lattina Women in Coffee — Pennika Rosa",
    category: "ground",
    collection: "pink-collection",
    packSize: "250 g tin",
    intensity: 6,
    price: 180000,
    image: "/products/shop/pink-collection__lattina-wic-pennika-rosa.png",
    description: {
      uz: "Rassom Pennika dizaynidagi pushti banka — Women in Coffee qahvasi.",
      ru: "Розовая банка с дизайном художницы Pennika — кофе Women in Coffee.",
      en: "Pink tin with artwork by Pennika — Women in Coffee coffee.",
    },
  },
  {
    id: "pink-mug",
    name: "Mug Women in Coffee",
    category: "accessories",
    collection: "pink-collection",
    packSize: "1 pc",
    intensity: null,
    price: 120000,
    image: "/products/shop/pink-collection__mug-per-women-in-coffee.png",
    description: {
      uz: "Women in Coffee loyihasining krujkasi.",
      ru: "Кружка проекта Women in Coffee.",
      en: "The Women in Coffee project mug.",
    },
  },
  {
    id: "pink-keep-cup",
    name: "Keep Cup Women in Coffee",
    category: "accessories",
    collection: "pink-collection",
    packSize: "1 pc",
    intensity: null,
    price: 150000,
    image: "/products/shop/pink-collection__keep-cup-wic.png",
    description: {
      uz: "Qayta ishlatiladigan Women in Coffee stakani — yo'lda qahva uchun.",
      ru: "Многоразовый стакан Women in Coffee — для кофе в дороге.",
      en: "Reusable Women in Coffee cup — for coffee on the go.",
    },
  },
  {
    id: "pink-tshirt",
    name: "T-Shirt Women in Coffee",
    category: "accessories",
    collection: "pink-collection",
    packSize: "M / L / XL",
    intensity: null,
    price: 190000,
    image: "/products/shop/pink-collection__t-shirt-wic-tg-m.png",
    description: {
      uz: "Women in Coffee futbolkasi.",
      ru: "Футболка Women in Coffee.",
      en: "Women in Coffee T-shirt.",
    },
  },
  {
    id: "pink-notebook-giallo",
    name: "Quaderno by Pennika — Giallo",
    category: "accessories",
    collection: "pink-collection",
    packSize: "1 pc",
    intensity: null,
    price: 60000,
    image: "/products/shop/pink-collection__quaderno-by-pennika-giallo.png",
    description: {
      uz: "Pennika dizaynidagi daftar — sariq.",
      ru: "Блокнот с дизайном Pennika — жёлтый.",
      en: "Notebook designed by Pennika — yellow.",
    },
  },
  {
    id: "pink-notebook-rosa",
    name: "Quaderno by Pennika — Rosa",
    category: "accessories",
    collection: "pink-collection",
    packSize: "1 pc",
    intensity: null,
    price: 60000,
    image: "/products/shop/pink-collection__quaderno-by-pennika-rosa.png",
    description: {
      uz: "Pennika dizaynidagi daftar — pushti.",
      ru: "Блокнот с дизайном Pennika — розовый.",
      en: "Notebook designed by Pennika — pink.",
    },
  },
  {
    id: "pink-notebook-viola",
    name: "Quaderno by Pennika — Viola",
    category: "accessories",
    collection: "pink-collection",
    packSize: "1 pc",
    intensity: null,
    price: 60000,
    image: "/products/shop/pink-collection__quaderno-by-pennika-viola.png",
    description: {
      uz: "Pennika dizaynidagi daftar — binafsha.",
      ru: "Блокнот с дизайном Pennika — фиолетовый.",
      en: "Notebook designed by Pennika — purple.",
    },
  },
  {
    id: "pink-notebook-bundle",
    name: "Bundle 3 quaderni Pennika",
    category: "accessories",
    collection: "pink-collection",
    packSize: "3 pcs",
    intensity: null,
    price: 160000,
    image: "/products/shop/pink-collection__bundle-3-quaderni-pennika.png",
    description: {
      uz: "Pennika dizaynidagi uchta daftar to'plami.",
      ru: "Набор из трёх блокнотов Pennika.",
      en: "Set of three Pennika notebooks.",
    },
  },
  {
    id: "pink-book",
    name: "Il fuoco sotto al caffè (EN)",
    category: "accessories",
    collection: "pink-collection",
    packSize: "Book",
    intensity: null,
    price: 220000,
    image: "/products/shop/pink-collection__il-fuoco-sotto-al-caffe-ed-inglese.png",
    description: {
      uz: "Caffè Vergnano tarixi haqidagi kitob — ingliz tilida.",
      ru: "Книга об истории Caffè Vergnano — на английском.",
      en: "The book on Caffè Vergnano's story — English edition.",
    },
  },
];

export const categories: Category[] = [
  "beans",
  "ground",
  "capsules",
  "pods",
  "accessories",
];

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("ru-RU").format(price);
}
