import type { Locale } from "./i18n";

export type Category = "beans" | "ground" | "capsules" | "pods" | "accessories";

// Vergnano product lines shown as the main navigation of the catalog.
export type Collection =
  | "riserva-torino"
  | "1882-line"
  | "classic-line"
  | "caffe-in-grani"
  | "single-origin"
  | "pink-collection"
  | "caffe-macinato";

// Order of the category cards on the products page. Each has its own page
// at /[locale]/[collection].
export const collections: Collection[] = [
  "riserva-torino",
  "1882-line",
  "classic-line",
  "caffe-in-grani",
  "single-origin",
  "pink-collection",
  "caffe-macinato",
];

export const collectionImages: Record<Collection | "all", string> = {
  "riserva-torino": "/images/riserva/riserva-torino-hero.jpg",
  "1882-line": "/images/lines/1882-line/linea-1882.jpg",
  "classic-line": "/images/lines/classic-line/linea-classica.jpg",
  "caffe-in-grani": "/images/categories/caffe-grani.jpg",
  "single-origin": "/images/lines/single-origin/hero-so.jpg",
  "pink-collection": "/images/categories/pink-collection.jpg",
  "caffe-macinato": "/images/categories/caffe-macinato.jpg",
  all: "/images/categories/moka-e-tazzine.jpg",
};

export interface Product {
  id: string;
  name: string;
  category: Category; // product form — drives detail-page facts
  collection: Collection | null; // catalog line; null = shown under "All" only
  packSize: string;
  intensity: number | null;
  // Retail price in UZS (from the official price list; wholesale prices are not shown online).
  price: number;
  image: string;
  description: Record<Locale, string>;
}

export const products: Product[] = [
  {
    id: "beans-antica-bottega",
    name: "Antica Bottega",
    category: "beans",
    collection: "caffe-in-grani",
    packSize: "1 kg",
    intensity: 5,
    price: 480000,
    image: "/products/beans-antica-bottega.png",
    description: {
      uz: "Antica Bottega — 100% saralangan arabikadan (Nikaragua, Kosta-Rika, Santo-Domingo, Braziliya) nafis, nozik kupaj: keskin og'ishlarsiz olijanob, yumshoq va yumaloq ta'm. Slow Roasting usulidagi o'rtacha qovurish vanil, yengil karamel va yangi tostning meva-gul tuslari bilan nozik xushbo'yligini ochadi. Ta'm muvozanatli: sut shokoladining nozik achchiqligi, yumaloq mevali nordonlik va ipakdek baxmal tana. Mayin yong'oqrang krema hamda bodom va karamelli toza shirin-qaymoqli ta'm. Intensivlik 5/10. Espresso, moka va kapuchino uchun ideal; italyan an'anasi ruhidagi novvoyxona, qandolatxona va kofexonalarga tavsiya etiladi.",
      ru: "Antica Bottega — элегантный, деликатный купаж из 100% отборной арабики (Никарагуа, Коста-Рика, Санто-Доминго, Бразилия): благородный, мягкий и округлый вкус без резких перекосов. Средняя обжарка Slow Roasting раскрывает тонкий аромат ванили, лёгкой карамели и свежего тоста с фруктово-цветочными нюансами. Вкус сбалансированный: деликатная горчинка молочного шоколада, округлая фруктовая кислинка и шелковистое бархатистое тело. Нежная ореховая пенка и чистое сладковато-сливочное послевкусие с миндалём и карамелью. Интенсивность 5/10. Идеален для эспрессо, мока-пота и капучино; рекомендован пекарням, кондитерским и кофейням в духе итальянской традиции.",
      en: "Antica Bottega is an elegant, delicate blend of 100% selected Arabica (Nicaragua, Costa Rica, Santo Domingo, Brazil): a noble, soft and round taste with no harsh edges. Medium slow roasting reveals a fine aroma of vanilla, light caramel and fresh toast with fruity-floral nuances. The cup is balanced: the gentle bitterness of milk chocolate, a round fruity acidity and a silky, velvety body. A soft hazelnut crema and a clean, sweet-creamy finish of almond and caramel. Intensity 5/10. Ideal for espresso, moka pot and cappuccino; recommended for bakeries, pastry shops and cafés in the Italian tradition.",
    },
  },
  {
    id: "beans-espresso",
    name: "Espresso Casa",
    category: "beans",
    collection: "caffe-in-grani",
    packSize: "1 kg",
    intensity: 7,
    price: 440000,
    image: "/products/beans-espresso.png",
    description: {
      uz: "Espresso Casa — Vergnano'ning iliq, to'yingan va xushbo'y kupaji: uy uslubidagi klassik italyan espressosini qadrlaydiganlar uchun — ortiqcha murakkabliksiz, ammo o'zgarmas sifat bilan. Tarkibi: arabika (Markaziy va Janubiy Amerika) yumshoqlik va yumaloqlik, robusta (Osiyo) zich tana va barqaror krema beradi. Slow Roasting usulidagi o'rtacha qovurish shinam, uyg'un profilni ochadi: qovurilgan don, kakao, shirinmiya va karamel, iliq o'rab oluvchi ta'm bilan. Quyuq krema va shokolad-karamel xushbo'yligi har chashkada haqiqiy italyan qahvasi hissini beradi. Intensivlik 7/10. Espresso, kapuchino va latte uchun ideal; ofislar, biznes markazlar va mehmonxonalarga tavsiya etiladi.",
      ru: "Espresso Casa — тёплый, насыщенный и душистый купаж Vergnano для тех, кто ценит классический итальянский эспрессо в домашнем стиле: без лишней сложности, но с неизменным качеством. Состав: арабика (Центральная и Южная Америка) даёт мягкость и округлость, робуста (Азия) — плотное тело и стойкую пенку. Средняя обжарка Slow Roasting раскрывает уютный, гармоничный профиль: обжаренное зерно, какао, лакрица и карамель с тёплым обволакивающим послевкусием. Густая пенка и шоколадно-карамельный аромат создают ощущение настоящего итальянского кофе в каждой чашке. Интенсивность 7/10. Идеален для эспрессо, капучино и латте; рекомендован офисам, бизнес-центрам и отелям.",
      en: "Espresso Casa is Vergnano's warm, rich and fragrant blend for those who love classic Italian espresso in the home style: no fuss, always the same quality. Blend: Arabica (Central and South America) brings softness and roundness, Robusta (Asia) a dense body and lasting crema. Medium slow roasting reveals a cosy, harmonious profile of roasted grain, cocoa, liquorice and caramel with a warm, enveloping finish. Thick crema and a chocolate-caramel aroma give the feeling of real Italian coffee in every cup. Intensity 7/10. Ideal for espresso, cappuccino and latte; recommended for offices, business centres and hotels.",
    },
  },
  {
    id: "beans-granaroma",
    name: "Granaroma",
    category: "beans",
    collection: "caffe-in-grani",
    packSize: "1 kg",
    intensity: 8,
    price: 400000,
    image: "/products/beans-granaroma.png",
    description: {
      uz: "Granaroma — Vergnano'ning eng mashhur va ramziy kupaji: boy, to'liq tanali va kuchli xushbo'y italyan espressosini qadrlaydiganlar uchun. Tarkibi: 60% arabika (Markaziy va Janubiy Amerika) yumshoq shirinlik va murakkablik, 40% robusta (Osiyo va Afrika) zich tana va kuch beradi. Slow Roasting usulidagi o'rtacha qovurish ko'p qatlamli profilni ochadi: kakao, yong'oq, solod, ziravorlar va quritilgan meva, uzoq shokoladli ta'm bilan. Siropsimon tekstura, quyuq barqaror krema va ziravor-shokoladli xushbo'ylik kupajni bexato tanitadi. Intensivlik 8/10. Espresso, kapuchino va latte uchun ideal; har qanday hajmdagi kofexona, restoran va novvoyxonalarga tavsiya etiladi.",
      ru: "Granaroma — самый популярный и знаковый купаж Vergnano для тех, кто ценит богатый, полнотелый и интенсивно ароматный итальянский эспрессо. Состав: 60% арабика (Центральная и Южная Америка) даёт мягкую сладость и комплексность, 40% робуста (Азия и Африка) — плотное тело и силу. Средняя обжарка Slow Roasting раскрывает многослойный профиль: какао, грецкий орех, солод, пряности и сухофрукты с долгим шоколадным послевкусием. Сиропообразная текстура, густая стойкая пенка и пряно-шоколадный аромат делают купаж безошибочно узнаваемым. Интенсивность 8/10. Идеален для эспрессо, капучино и латте; рекомендован кофейням, ресторанам и пекарням любого масштаба.",
      en: "Granaroma is Vergnano's most popular and iconic blend, for those who love a rich, full-bodied, intensely aromatic Italian espresso. Blend: 60% Arabica (Central and South America) brings soft sweetness and complexity, 40% Robusta (Asia and Africa) gives a dense body and strength. Medium slow roasting reveals a layered profile of cocoa, walnut, malt, spices and dried fruit with a long chocolate finish. A syrupy texture, thick lasting crema and spicy-chocolate aroma make this blend unmistakable. Intensity 8/10. Ideal for espresso, cappuccino and latte; recommended for cafés, restaurants and bakeries of any size.",
    },
  },
  {
    id: "beans-arabica",
    name: "100% Arabica",
    category: "beans",
    collection: "caffe-in-grani",
    packSize: "250 g",
    intensity: 4,
    price: 170000,
    image: "/products/beans-arabica.png",
    description: {
      uz: "100% arabikadan xushbo'y kupaj — muvozanatli, tabiiy shirinlik va nozik mevali xarakter bilan. Tarkibi: Markaziy va Janubiy Amerika hamda Afrikaning saralangan arabikasi. Shokolad, funduk, yong'oq, solod va karamel notalari. Slow Roasting usulidagi o'rtacha qovurish donlarning mevali va gulli tuslarini ochadi. Intensivlik 4/10. Espresso mashinasi, moka, purover va drip qahva uchun ideal.",
      ru: "Ароматный купаж из 100% арабики — сбалансированный, с природной сладостью и деликатным фруктовым характером. Состав: отборная арабика Центральной и Южной Америки и Африки. Ноты шоколада, фундука, грецкого ореха, солода и карамели. Средняя обжарка Slow Roasting раскрывает фруктовые и цветочные оттенки зёрен. Интенсивность 4/10. Идеален для эспрессо-машины, мока-пота, пуровера и дрип-кофе.",
      en: "A fragrant 100% Arabica blend — balanced, with natural sweetness and a delicate fruity character. Blend: selected Arabica from Central and South America and Africa. Notes of chocolate, hazelnut, walnut, malt and caramel. Medium slow roasting brings out the beans' fruity and floral nuances. Intensity 4/10. Ideal for espresso machine, moka pot, pour-over and drip coffee.",
    },
  },
  {
    id: "ground-granaroma",
    name: "Granaroma Macinato",
    category: "ground",
    collection: "caffe-macinato",
    packSize: "250 g",
    intensity: 7,
    price: 120000,
    image: "/products/ground-granaroma.png",
    description: {
      uz: "Granaroma — to'yingan, yorqin xarakterli va barqaror xushbo'y klassik italyan kupaji. Arabika va robusta uyg'unligi kakao, quritilgan meva, chinnigul, yong'oq va non qobig'i notalari bilan boy profilni ochadi — uzoq ta'mli zich, xushbo'y qahva. O'rtacha qovurish. Vakuum qadoqdagi maydalangan qahva, 250 g. Intensivlik 7/10.",
      ru: "Granaroma — классический итальянский бленд с насыщенным, выразительным характером и стойким ароматом. Гармония арабики и робусты раскрывает богатый профиль с нотами какао, сухофруктов, гвоздики, орехов и хлебной корочки — плотный ароматный кофе с долгим послевкусием. Средняя обжарка. Молотый кофе в вакуумной упаковке, 250 г. Интенсивность 7/10.",
      en: "Granaroma is a classic Italian blend with a rich, expressive character and a lasting aroma. The harmony of Arabica and Robusta opens a generous profile of cocoa, dried fruit, clove, nuts and bread crust — a dense, fragrant coffee with a long finish. Medium roast. Ground coffee, vacuum-packed, 250 g. Intensity 7/10.",
    },
  },
  {
    id: "ground-antica-bottega",
    name: "Antica Bottega Macinato",
    category: "ground",
    collection: "caffe-macinato",
    packSize: "250 g",
    intensity: 4,
    price: 140000,
    image: "/products/ground-antica-bottega.png",
    description: {
      uz: "Antica Bottega — yumshoq, shirin va uyg'un xarakterli nafis klassik aralashma. Markaziy Amerika saralangan arabikasi robusta bilan birga mayin xushbo'ylik hamda shokolad va amaretto notalari, yengil nordonlik va uzoq yoqimli ta'mli yumaloq ta'mni ochadi. Sekin o'rtacha qovurish tabiiy shirinlikni ta'kidlaydi. Vakuum qadoqdagi maydalangan qahva, 250 g. Intensivlik 4/10.",
      ru: "Antica Bottega — утончённая классическая смесь с мягким, сладким и гармоничным характером. Отборная центральноамериканская арабика в сочетании с робустой раскрывает нежный аромат и округлый вкус с нотами шоколада и амаретто, лёгкой кислотностью и долгим приятным послевкусием. Медленная средняя обжарка подчёркивает природную сладость. Молотый кофе в вакуумной упаковке, 250 г. Интенсивность 4/10.",
      en: "Antica Bottega is a refined classic blend with a soft, sweet and harmonious character. Selected Central American Arabica combined with Robusta gives a gentle aroma and a round taste with notes of chocolate and amaretto, light acidity and a long, pleasant finish. Slow medium roasting highlights its natural sweetness. Ground coffee, vacuum-packed, 250 g. Intensity 4/10.",
    },
  },
  {
    id: "ground-espressocasa",
    name: "Espresso Casa Macinato",
    category: "ground",
    collection: "caffe-macinato",
    packSize: "250 g",
    intensity: 8,
    price: 130000,
    image: "/products/ground-espressocasa.png",
    description: {
      uz: "Espresso Casa — uy espressosi uchun klassik italyan aralashmasi: har chashkada to'yingan ta'm va zich krema. Mayda tortilgan qahva to'liq tanali, yorqin ta'm va nozik ziravor tuslari bilan boy xushbo'ylikni ochadi. Arabika va robusta aralashmasi, o'rtacha qovurish. Vakuum qadoqdagi maydalangan qahva, 250 g. Intensivlik 8/10.",
      ru: "Espresso Casa — классическая итальянская смесь для домашнего эспрессо: насыщенный вкус и плотная крема в каждой чашке. Тонкий помол раскрывает полнотелый, выразительный вкус и богатый аромат с деликатными пряными оттенками. Смесь арабики и робусты, средняя обжарка. Молотый кофе в вакуумной упаковке, 250 г. Интенсивность 8/10.",
      en: "Espresso Casa is the classic Italian blend for espresso at home: a rich taste and thick crema in every cup. The fine grind reveals a full-bodied, expressive flavour and a generous aroma with delicate spicy notes. Arabica and Robusta blend, medium roast. Ground coffee, vacuum-packed, 250 g. Intensity 8/10.",
    },
  },
  {
    id: "ground-arabica-tin",
    name: "100% Arabica Lattina",
    category: "ground",
    collection: "caffe-macinato",
    packSize: "250 g tin",
    intensity: 7,
    price: 150000,
    image: "/products/ground-arabica-tin.png",
    description: {
      uz: "Mashhur Vergnano bankasidagi premium Arabica, espresso uchun maydalangan. Muvozanatli, mevali va yumaloq aromat.",
      ru: "Премиальная арабика в легендарной банке Vergnano, помол для эспрессо. Сбалансированный, фруктовый, округлый вкус.",
      en: "Premium Arabica in the iconic Vergnano tin, ground for espresso. Balanced and fruity with a rounded aroma.",
    },
  },
  {
    id: "caps-cremoso",
    name: "Cremoso",
    category: "capsules",
    collection: null,
    packSize: "30 capsules · Nespresso®*",
    intensity: 6,
    price: 195000,
    image: "/products/caps-cremoso.png",
    description: {
      uz: "Yong'oq va kakao notalari bilan mayin, barqaror aralashma — boy, baxmal espresso. Kompostlanadigan kapsulalar.",
      ru: "Мягкая, стойкая смесь с ореховыми и какао-нотами — насыщенный бархатный эспрессо. Компостируемые капсулы.",
      en: "A soft, persistent blend with nutty aromas and cocoa notes — a rich, velvety espresso. Compostable capsules.",
    },
  },
  {
    id: "caps-intenso",
    name: "Intenso Èspresso 1882",
    category: "capsules",
    collection: null,
    packSize: "30 capsules · Nespresso®*",
    intensity: 8,
    price: 195000,
    image: "/products/caps-intenso.png",
    description: {
      uz: "Qat'iy va to'liq tanali — shokolad va ziravor notalari Amerika Arabikasi bilan yumshatilgan. Kompostlanadigan kapsulalar.",
      ru: "Решительный и полнотелый — шоколадные и пряные ноты, смягчённые американской арабикой. Компостируемые капсулы.",
      en: "Decisive and full-bodied, with chocolatey, spicy notes softened by smooth American Arabica. Compostable capsules.",
    },
  },
  {
    id: "caps-arabica",
    name: "100% Arabica Capsule",
    category: "capsules",
    collection: null,
    packSize: "30 capsules · Nespresso®*",
    intensity: 4,
    price: 195000,
    image: "/products/caps-arabica.png",
    description: {
      uz: "Nozik va muvozanatli — sariq meva, vanil, karamel va sut shokoladi notalari. Kompostlanadigan kapsulalar.",
      ru: "Деликатный и сбалансированный — ноты жёлтых фруктов, ванили, карамели и молочного шоколада. Компостируемые капсулы.",
      en: "Delicate and balanced — notes of yellow fruit, vanilla, caramel and milk chocolate. Compostable capsules.",
    },
  },
  {
    id: "caps-decaf",
    name: "Decaffeinato",
    category: "capsules",
    collection: null,
    packSize: "30 capsules · Nespresso®*",
    intensity: 5,
    price: 195000,
    image: "/products/caps-decaf.png",
    description: {
      uz: "Nafis kofeinsiz qahva — sitrus, qizil meva, choy va sut shokoladi notalari. Kompostlanadigan kapsulalar.",
      ru: "Элегантный декаф — ноты цитрусов, красных ягод, чая и молочного шоколада. Компостируемые капсулы.",
      en: "An elegant decaf with bright notes of citrus, red fruits, tea and milk chocolate. Compostable capsules.",
    },
  },
  {
    id: "caps-oro-50",
    name: "Oro",
    category: "capsules",
    collection: null,
    packSize: "50 capsules · Nespresso®*",
    intensity: 4,
    price: 280000,
    image: "/products/caps-oro-50.png",
    description: {
      uz: "Nozik, muvozanatli aralashma — meva va vanil notalari, karamel shirinligi. Tejamkor 50 talik quti.",
      ru: "Деликатная сбалансированная смесь — фруктово-ванильные ноты со сладостью карамели. Выгодная упаковка из 50 капсул.",
      en: "A delicate, balanced blend with fruit and vanilla notes plus caramel sweetness. Value 50-pack.",
    },
  },
  {
    id: "pods-espresso-150",
    name: "Espresso Cialde",
    category: "pods",
    collection: null,
    packSize: "150 ESE pods",
    intensity: 7,
    price: 590000,
    image: "/products/pods-espresso-150.png",
    description: {
      uz: "Boy va kremali ESE qog'oz chaldalar — to'liq ta'm, kuchli aromat va quyuq krema. Kompostlanadigan.",
      ru: "Насыщенные кремовые чалды ESE — полный вкус, интенсивный аромат и плотная крема. Компостируемые.",
      en: "Rich, creamy ESE paper pods — full-bodied taste, intense aroma and a dense crema. Compostable.",
    },
  },
  {
    id: "pods-oro-150",
    name: "Oro Cialde",
    category: "pods",
    collection: null,
    packSize: "150 ESE pods",
    intensity: 5,
    price: 590000,
    image: "/products/pods-oro-150.png",
    description: {
      uz: "Nozik va muvozanatli ESE chaldalar — yumshoq, to'liq ta'm va yorqin aromat. Kompostlanadigan.",
      ru: "Деликатные сбалансированные чалды ESE — мягкий полный вкус и выраженный аромат. Компостируемые.",
      en: "Delicate, balanced ESE pods with a smooth, full taste and pronounced fragrance. Compostable.",
    },
  },
  {
    id: "acc-moka-nera",
    name: "Moka Nera",
    category: "accessories",
    collection: null,
    packSize: "3 cups",
    intensity: null,
    price: 450000,
    image: "/products/acc-moka-nera.png",
    description: {
      uz: "Vergnano brendidagi matoviy qora moka — uyda qahva tayyorlashning klassik italyan usuli.",
      ru: "Гейзерная кофеварка Vergnano в матовом чёрном цвете — классический итальянский способ варить кофе дома.",
      en: "A Vergnano-branded matte black stovetop moka pot — the classic Italian way to brew at home.",
    },
  },
  {
    id: "acc-tazzine-rosse",
    name: "Set da 6 Tazzine Rosse",
    category: "accessories",
    collection: null,
    packSize: "6 cups + saucers",
    intensity: null,
    price: 650000,
    image: "/products/acc-tazzine-rosse.png",
    description: {
      uz: "Olti dona qizil Caffè Vergnano espresso finjonlari — uyingizda haqiqiy 1882 bar uslubi.",
      ru: "Набор из шести красных эспрессо-чашек Caffè Vergnano — фирменный стиль бара 1882 у вас дома.",
      en: "Set of six red Caffè Vergnano espresso cups with saucers — the signature 1882 bar look at home.",
    },
  },

  // ---- Vergnano lines & shop range (images from caffevergnano.com) ----
  {
    id: "rt-nobile",
    name: "Riserva Torino Nobile",
    category: "beans",
    collection: "riserva-torino",
    packSize: "1 kg",
    intensity: 6,
    price: 440000,
    image: "/images/riserva/riserva-torino-nobile.png",
    description: {
      uz: "Nobile — Riserva Torino liniyasining nafis kupaji, italyan qahva madaniyati poytaxti Turinning qahva merosidan ilhomlangan. Tarkibi: o'ziga xos qiyomli shirinlikka ega Markaziy va Janubiy Amerika saralangan arabikasi hamda shokoladli chuqurlik va tuzilma beruvchi Osiyo robustasi. Slow Roasting usulidagi o'rtacha-yengil qovurish donlarning nozikligini zarracha achchiqliksiz ochadi. Profil: kakao, pishiriq, don va karamel — mayin shirinlik, nafis tana va toza uzoq ta'mli baxmal, sayqallangan espresso. Intensivlik 6/10. Rainforest Alliance sertifikati. Espresso, amerikano, kapuchino va latte uchun ideal; mehmonxonalar, fine dining restoranlar va premium kofexonalarga tavsiya etiladi.",
      ru: "Nobile — утончённый купаж линейки Riserva Torino, вдохновлённый кофейным наследием Турина, столицы итальянской кофейной культуры. Состав: отборная арабика Центральной и Южной Америки с характерной пастообразной сладостью, дополненная азиатской робустой, дающей шоколадную глубину и структуру. Средне-лёгкая обжарка Slow Roasting раскрывает деликатность зёрен без малейшей горечи. Профиль: какао, выпечка, злаки и карамель — бархатистый, рафинированный эспрессо с нежной сладостью, элегантным телом и чистым долгим послевкусием. Интенсивность 6/10. Сертификат Rainforest Alliance. Идеален для эспрессо, американо, капучино и латте; рекомендован отелям, ресторанам fine dining и премиум-кофейням.",
      en: "Nobile is the refined blend of the Riserva Torino line, inspired by the coffee heritage of Turin, the capital of Italian coffee culture. Blend: selected Central and South American Arabica with its typical syrupy sweetness, complemented by Asian Robusta for chocolate depth and structure. Medium-light slow roasting reveals the delicacy of the beans without a hint of bitterness. Profile: cocoa, pastry, cereals and caramel — a velvety, refined espresso with gentle sweetness, an elegant body and a clean, long finish. Intensity 6/10. Rainforest Alliance certified. Ideal for espresso, americano, cappuccino and latte; recommended for hotels, fine-dining restaurants and premium cafés.",
    },
  },
  {
    id: "rt-arabica",
    name: "Riserva Torino 100% Arabica",
    category: "beans",
    collection: "riserva-torino",
    packSize: "1 kg",
    intensity: 4,
    price: 490000,
    image: "/images/riserva/arabica-rt-1.png",
    description: {
      uz: "Arabica 100% — Riserva Torino liniyasining premium kupaji, Italiyaning tarixiy qahva poytaxti Turinga ehtirom. Tarkibi: 100% arabika — Markaziy va Janubiy Amerikaning yuvilgan baland tog' donlari hamda tanaga chuqurlik, yengil kakao va vanil notalarini beruvchi yarim yuvilgan Afrika arabikasi. Slow Roasting usulidagi o'rtacha-yengil qovurish donning tabiiy gulli, mevali va shirin xususiyatlarini ochadi. Profil: don, shokolad, yong'oq, vanil va bodom — mayin nordonlik va toza uzoq ta'mli silliq, nozik espresso. Intensivlik 4/10, xushbo'ylik 6/10. Espresso, moka, filtr va puroverga ideal; specialty kofexonalar, fine dining restoranlar va mehmonxonalarga tavsiya etiladi.",
      ru: "Arabica 100% — премиальный купаж линейки Riserva Torino, дань уважения Турину, исторической кофейной столице Италии. Состав: 100% арабика — мытые высокогорные зёрна Центральной и Южной Америки, дополненные полумытой африканской арабикой, которая даёт телу глубину и лёгкие ноты какао и ванили. Средне-лёгкая обжарка Slow Roasting раскрывает природные цветочные, фруктовые и сладкие характеристики зерна. Профиль: злаки, шоколад, грецкий орех, ваниль и миндаль — гладкий, деликатный эспрессо с нежной кислотностью и чистым долгим послевкусием. Интенсивность 4/10, аромат 6/10. Идеален для эспрессо, мока-пота, фильтра и пуровера; рекомендован specialty-кофейням, ресторанам fine dining и отелям.",
      en: "Arabica 100% is the premium blend of the Riserva Torino line, a tribute to Turin, Italy's historic coffee capital. Blend: 100% Arabica — washed high-altitude beans from Central and South America, complemented by semi-washed African Arabica that adds depth and light notes of cocoa and vanilla. Medium-light slow roasting brings out the bean's natural floral, fruity and sweet character. Profile: cereals, chocolate, walnut, vanilla and almond — a smooth, delicate espresso with gentle acidity and a clean, long finish. Intensity 4/10, aroma 6/10. Ideal for espresso, moka pot, filter and pour-over; recommended for specialty cafés, fine-dining restaurants and hotels.",
    },
  },
  {
    id: "rt-cremoso",
    name: "Riserva Torino Cremoso",
    category: "beans",
    collection: "riserva-torino",
    packSize: "1 kg",
    intensity: 8,
    price: 400000,
    image: "/images/riserva/cremoso-rt-1.png",
    description: {
      uz: "Cremoso — Riserva Torino liniyasining to'yingan, to'liq tanali kupaji: xarakterli va chuqur boy italyan espressosini qadrlaydiganlar uchun. Tarkibi: bir necha mintaqadan saralangan arabika va kuchli tuzilma, quyuq krema hamda shokoladli to'yinganlik beruvchi saralangan robusta. Slow Roasting usulidagi o'rtacha qovurish xushbo'ylik boyligi va ta'm kuchini ochadi, silliqlik va nafislikni saqlab qoladi. Profil: yong'oq, chinnigul, shirinmiya va qarsildoq non qobig'i — zich tanali, oltin tusli ixcham yong'oqrang kremali va uzoq ta'mli kuchli espresso. Intensivlik 8/10. Espresso, kapuchino, doppio va makkiato uchun ideal; premium kofexonalar, restoranlar va 4–5 yulduzli mehmonxonalarga tavsiya etiladi.",
      ru: "Cremoso — насыщенный, полнотелый купаж линейки Riserva Torino для тех, кто ценит богатый итальянский эспрессо с характером и глубиной. Состав: отборная арабика нескольких регионов в сочетании с отборной робустой, дающей мощную структуру, густую пенку и шоколадную насыщенность. Средняя обжарка Slow Roasting раскрывает богатство аромата и интенсивность вкуса, сохраняя гладкость и элегантность. Профиль: орехи, гвоздика, лакрица и хрустящая хлебная корочка — интенсивный стойкий эспрессо с плотным телом, компактной ореховой пенкой с золотыми оттенками и долгим послевкусием. Интенсивность 8/10. Идеален для эспрессо, капучино, доппио и маккиато; рекомендован премиум-кофейням, ресторанам и отелям 4–5 звёзд.",
      en: "Cremoso is the rich, full-bodied blend of the Riserva Torino line, made for those who love a bold Italian espresso with character and depth. Blend: selected Arabica from several origins combined with fine Robusta, which brings powerful structure, thick crema and chocolate richness. Medium slow roasting unlocks the aroma and intensity while keeping the cup smooth and elegant. Profile: nuts, clove, liquorice and crisp bread crust — an intense, persistent espresso with a dense body, a compact hazelnut crema with golden highlights and a long finish. Intensity 8/10. Ideal for espresso, cappuccino, doppio and macchiato; recommended for premium cafés, restaurants and 4–5 star hotels.",
    },
  },
  {
    id: "rt-caps-nobile",
    name: "Riserva Torino Nobile — Capsule",
    category: "capsules",
    collection: "riserva-torino",
    packSize: "10 capsules · Nespresso®*",
    intensity: 6,
    price: 90000,
    image: "/images/riserva/capsules.png",
    description: {
      uz: "Nobile — Riserva Torino premium kolleksiyasining nafis blendi: yumshoq, muvozanatli italyan espressosini qadrlaydiganlar uchun. Saralangan arabika va robusta sut shokoladi, karamel, qovurilgan funduk va quritilgan meva notalari hamda yengil ziravor tuslari bilan nozik ta'm beradi. To'yingan xushbo'ylik, baxmal tekstura, zich oltin krema va uzoq shirin ta'm. O'rtacha qovurish. Kapsulalar, 10 dona, Nespresso® Original bilan mos. Intensivlik 6/10.",
      ru: "Nobile — элегантный бленд премиальной коллекции Riserva Torino для ценителей мягкого, сбалансированного итальянского эспрессо. Отборные арабика и робуста дают изысканный вкус с нотами молочного шоколада, карамели, жареного фундука и сухофруктов с лёгкими пряными оттенками. Насыщенный аромат, бархатистая текстура, плотная золотистая крема и долгое сладкое послевкусие. Средняя обжарка. Капсулы, 10 шт., совместимы с Nespresso® Original. Интенсивность 6/10.",
      en: "Nobile is the elegant blend of the premium Riserva Torino collection, for lovers of a smooth, balanced Italian espresso. Selected Arabica and Robusta give a refined taste with notes of milk chocolate, caramel, roasted hazelnut and dried fruit, touched with light spice. A rich aroma, velvety texture, dense golden crema and a long, sweet finish. Medium roast. Capsules, 10 pcs, compatible with Nespresso® Original. Intensity 6/10.",
    },
  },
  {
    id: "rt-caps-arabica",
    name: "Riserva Torino 100% Arabica — Capsule",
    category: "capsules",
    collection: "riserva-torino",
    packSize: "10 capsules · Nespresso®*",
    intensity: 4,
    price: 100000,
    image: "/images/riserva/capsules.png",
    description: {
      uz: "Arabica 100% — Riserva Torino premium kolleksiyasining eng yaxshi 100% arabika navlaridan eksklyuziv blendi. Nozik xushbo'ylik va sut shokoladi, karamel, sitrus va pishgan meva notalari bilan nafis ta'm, nozik gulli shirinlik bilan. Baxmal tekstura, muvozanatli nordonlik va uzoq ta'm har chashkani chinakam nafis qiladi. O'rtacha qovurish. Kapsulalar, 10 dona, Nespresso® Original bilan mos. Intensivlik 4/10.",
      ru: "Arabica 100% — эксклюзивный бленд премиальной коллекции Riserva Torino из лучших сортов 100% арабики. Утончённый аромат и элегантный вкус с нотами молочного шоколада, карамели, цитрусовых и спелых фруктов с деликатной цветочной сладостью. Бархатистая текстура, сбалансированная кислотность и долгое послевкусие делают каждую чашку по-настоящему изысканной. Средняя обжарка. Капсулы, 10 шт., совместимы с Nespresso® Original. Интенсивность 4/10.",
      en: "Arabica 100% is the exclusive blend of the premium Riserva Torino collection, made from the finest 100% Arabica. A refined aroma and elegant taste with notes of milk chocolate, caramel, citrus and ripe fruit, with a delicate floral sweetness. A velvety texture, balanced acidity and long finish make every cup truly exquisite. Medium roast. Capsules, 10 pcs, compatible with Nespresso® Original. Intensity 4/10.",
    },
  },
  {
    id: "rt-caps-cremoso",
    name: "Riserva Torino Cremoso — Capsule",
    category: "capsules",
    collection: "riserva-torino",
    packSize: "10 capsules · Nespresso®*",
    intensity: 10,
    price: 85000,
    image: "/images/riserva/capsules.png",
    description: {
      uz: "Cremoso — Riserva Torino kolleksiyasining uyg'un ta'm va to'yingan xushbo'ylikka ega premium blendi. Saralangan arabika va robusta kakao, qovurilgan yong'oq va don notalari bilan ochiladi — baxmal tekstura, zich tana va barqaror oltin krema. O'rtacha qovurish yumshoqlik, shirinlik va olijanob achchiqlik muvozanatini beradi. Kapsulalar, 10 dona, Nespresso® Original bilan mos. Intensivlik 10/10.",
      ru: "Cremoso — премиальный бленд коллекции Riserva Torino с гармоничным вкусом и насыщенным ароматом. Отборные арабика и робуста раскрываются нотами какао, жареных орехов и злаков — бархатистая текстура, плотное тело и стойкая золотистая крема. Средняя обжарка даёт баланс мягкости, сладости и благородной горчинки. Капсулы, 10 шт., совместимы с Nespresso® Original. Интенсивность 10/10.",
      en: "Cremoso is the premium blend of the Riserva Torino collection, with a harmonious taste and rich aroma. Selected Arabica and Robusta open with notes of cocoa, roasted nuts and cereals — a velvety texture, dense body and lasting golden crema. Medium roasting balances softness, sweetness and a noble bitterness. Capsules, 10 pcs, compatible with Nespresso® Original. Intensity 10/10.",
    },
  },
  {
    id: "l1882-original",
    name: "1882 Original",
    category: "beans",
    collection: "1882-line",
    packSize: "2,5 kg",
    intensity: 7,
    price: 950000,
    image: "/images/lines/1882-line/linea-1882-original.png",
    description: {
      uz: "O'rtacha qovurish — meva va asal notalari bilan nozik, xushbo'y aralashma; shokolad nozikliklari va quyuq krema.",
      ru: "Средняя обжарка — деликатная ароматная смесь с нотами фруктов и мёда; шоколадные нюансы и плотная крема.",
      en: "Medium roast — a delicate, aromatic blend with hints of fruit and honey; chocolate notes and a dense crema.",
    },
  },
  {
    id: "l1882-strong",
    name: "1882 Strong",
    category: "beans",
    collection: "1882-line",
    packSize: "2,5 kg",
    intensity: 9,
    price: 950000,
    image: "/images/lines/1882-line/linea-1882-strong.png",
    description: {
      uz: "Kuchli va to'yingan — Janubiy Amerika va Osiyo Robustalarining quyuq, uzoq davom etuvchi ta'mi.",
      ru: "Крепкий и насыщенный — плотный, стойкий вкус робусты Южной Америки и Азии.",
      en: "Strong and full-bodied — a dense, long-lasting taste from South American and Asian Robustas.",
    },
  },
  {
    id: "l1882-very-strong",
    name: "1882 Very Strong",
    category: "beans",
    collection: "1882-line",
    packSize: "2,5 kg",
    intensity: 10,
    price: 950000,
    image: "/images/lines/1882-line/linea-1882-very-strong.png",
    description: {
      uz: "Eng kuchli 1882 aralashmasi — juda intensiv, kuchli tanali espresso.",
      ru: "Самая крепкая смесь 1882 — очень интенсивный, полнотелый эспрессо.",
      en: "The strongest 1882 blend — a very intense, full-bodied espresso.",
    },
  },
  {
    id: "l1882-arabica",
    name: "1882 100% Arabica",
    category: "beans",
    collection: "1882-line",
    packSize: "2,5 kg",
    intensity: 6,
    price: 1050000,
    image: "/images/lines/1882-line/linea-1882-100-arabica.png",
    description: {
      uz: "100% Arabica — muvozanatli, xushbo'y va yumshoq, bar uchun ideal.",
      ru: "100% арабика — сбалансированный, ароматный и мягкий, идеален для бара.",
      en: "100% Arabica — balanced, aromatic and smooth, ideal for the bar.",
    },
  },
  {
    id: "cl-1000",
    name: "1000 Mille — Extra Dolce",
    category: "beans",
    collection: "classic-line",
    packSize: "1 kg",
    intensity: 5,
    price: 430000,
    image: "/images/lines/classic-line/linea-classica-100.jpg",
    description: {
      uz: "Juda shirin espresso — eng yumshoq Classic Line aralashmasi.",
      ru: "Экстра-сладкий эспрессо — самая мягкая смесь Classic Line.",
      en: "Extra-sweet espresso — the smoothest blend in the Classic Line.",
    },
  },
  {
    id: "cl-900",
    name: "900 Novecento — Dolce",
    category: "beans",
    collection: "classic-line",
    packSize: "1 kg",
    intensity: 6,
    price: 410000,
    image: "/images/lines/classic-line/linea-classica-900.jpg",
    description: {
      uz: "Shirin espresso — 90% Arabica, muvozanatli va xushbo'y.",
      ru: "Сладкий эспрессо — 90% арабики, сбалансированный и ароматный.",
      en: "Sweet espresso — 90% Arabica, balanced and aromatic.",
    },
  },
  {
    id: "cl-800",
    name: "800 Ottocento — Crema",
    category: "beans",
    collection: "classic-line",
    packSize: "1 kg",
    intensity: 6,
    price: 500000,
    image: "/images/lines/classic-line/linea-classica-800.jpg",
    description: {
      uz: "Crema 800 — Vergnano klassik liniyasining «oltin o'rtasi»: yumshoq, nozik xushbo'y va to'liq tanali kupaj, xushbo'ylik va qiyomning benuqson muvozanati. Xushbo'y, yengil, ammo boy va o'rab oluvchi espressoni qadrlaydiganlar uchun liniyaning uyg'unlik etaloni. Tarkibi: 80% arabika (Gvatemala va Nikaragua, qo'lda terilgan), 20% robusta (plantatsiya, Hindiston). Slow Roasting usulidagi o'rtacha qovurish tabiiy shirinlik va shokoladli xushbo'ylikni ochadi. Profil: nozik shokolad va qovurilgan yong'oq, yengil, ammo to'liq tana, yorqin shirinlik, yengil jimirlashli shirin yakun. Intensivlik 6/10. Espresso, amerikano, kapuchino va latte uchun ideal; kofexona, restoran va novvoyxonalarga tavsiya etiladi.",
      ru: "Crema 800 — «золотая середина» классической линейки Vergnano: мягкий, деликатно ароматный и полнотелый купаж с безупречным балансом аромата и консистенции. Эталон гармонии линейки для тех, кто ценит душистый, лёгкий, но богатый и обволакивающий эспрессо. Состав: 80% арабика (Гватемала и Никарагуа, ручной сбор), 20% робуста (плантационная, Индия). Средняя обжарка Slow Roasting раскрывает природную сладость и шоколадный аромат. Профиль: нежный шоколад и жареные орехи, лёгкое, но полное тело, выраженная сладость, сладковатый финиш с лёгким покалыванием. Интенсивность 6/10. Идеален для эспрессо, американо, капучино и латте; рекомендован кофейням, ресторанам и пекарням.",
      en: "Crema 800 is the golden mean of Vergnano's classic line: a smooth, delicately aromatic, full-bodied blend with a flawless balance of aroma and texture. The line's benchmark of harmony for those who want a fragrant, light yet rich and enveloping espresso. Blend: 80% Arabica (hand-picked in Guatemala and Nicaragua), 20% plantation Robusta (India). Medium slow roasting reveals natural sweetness and a chocolate aroma. Profile: gentle chocolate and roasted nuts, a light but full body, pronounced sweetness and a sweet finish with a slight tingle. Intensity 6/10. Ideal for espresso, americano, cappuccino and latte; recommended for cafés, restaurants and bakeries.",
    },
  },
  {
    id: "cl-700",
    name: "700 Settecento — Ricco",
    category: "beans",
    collection: "classic-line",
    packSize: "1 kg",
    intensity: 8,
    price: 370000,
    image: "/images/lines/classic-line/linea-classica-700.jpg",
    description: {
      uz: "Boy va kuchli — 70% Arabica, 30% Robusta.",
      ru: "Насыщенный и интенсивный — 70% арабики, 30% робусты.",
      en: "Rich and intense — 70% Arabica, 30% Robusta.",
    },
  },
  {
    id: "cl-600",
    name: "600 Seicento — Classico",
    category: "beans",
    collection: "classic-line",
    packSize: "1 kg",
    intensity: 8,
    price: 425000,
    image: "/images/lines/classic-line/linea-classica-600.jpg",
    description: {
      uz: "Classico 600 — Vergnano klassik liniyasining eng to'yingan va dadil kupaji: to'liq, yumaloq va kuchli xarakter. Robusta ulushi eng yuqori bo'lgani uchun uzoq va yorqin ta'm qoldiradi. Tarkibi: 60% arabika (Markaziy va Janubiy Amerika), 40% robusta (Afrika). Slow Roasting usulidagi o'rtacha-quyuq qovurish donlarga shokoladli xushbo'ylik va chuqur ta'm beradi. Profil: shokolad va jigarrang ziravorlar hidi, kakao achchiqligi bilan zich tana, kuygan shakar shirinligi, yumaloq shokoladli yakun; barqaror yong'oqrang krema. Intensivlik 8/10. Espresso, doppio va sutli ichimliklar uchun ideal; gavjum kofexona va restoranlarga tavsiya etiladi.",
      ru: "Classico 600 — самый насыщенный и смелый купаж классической линейки Vergnano с полным, округлым и интенсивным характером. Наибольшая доля робусты даёт долгое выраженное послевкусие. Состав: 60% арабика (Центральная и Южная Америка), 40% робуста (Африка). Средне-тёмная обжарка Slow Roasting придаёт зёрнам шоколадный аромат и глубину вкуса. Профиль: аромат шоколада и коричневых пряностей, плотное тело с горчинкой какао, сладость жжёного сахара, округлый шоколадный финиш; стойкая ореховая пенка. Интенсивность 8/10. Идеален для эспрессо, доппио и напитков на молоке; рекомендован кофейням и ресторанам с высокой проходимостью.",
      en: "Classico 600 is the richest, boldest blend in Vergnano's classic line, with a full, round and intense character. The highest share of Robusta gives a long, pronounced aftertaste. Blend: 60% Arabica (Central and South America), 40% Robusta (Africa). Medium-dark slow roasting brings out a chocolate aroma and depth of flavour. Profile: chocolate and brown spice on the nose, a dense body with cocoa bitterness, burnt-sugar sweetness and a round chocolate finish; a stable hazelnut-coloured crema. Intensity 8/10. Ideal for espresso, doppio and milk drinks; recommended for busy cafés and restaurants.",
    },
  },
  {
    id: "cl-500",
    name: "500 Cinquecento — Intenso",
    category: "beans",
    collection: "classic-line",
    packSize: "1 kg",
    intensity: 10,
    price: 340000,
    image: "/images/lines/classic-line/linea-classica-500.jpg",
    description: {
      uz: "Eng intensiv Classic Line aralashmasi — 50% Arabica, 50% Robusta.",
      ru: "Самая интенсивная смесь Classic Line — 50% арабики, 50% робусты.",
      en: "The most intense Classic Line blend — 50% Arabica, 50% Robusta.",
    },
  },
  {
    id: "cl-arabica-bio",
    name: "Arabica Bio",
    category: "beans",
    collection: "classic-line",
    packSize: "1 kg",
    intensity: 6,
    price: 450000,
    image: "/images/lines/classic-line/linea-classica-arabica-bio.jpg",
    description: {
      uz: "Sertifikatlangan organik 100% Arabica.",
      ru: "Сертифицированная органическая 100% арабика.",
      en: "Certified organic 100% Arabica.",
    },
  },
  {
    id: "cl-decaf",
    name: "Decaffeinato",
    category: "beans",
    collection: "classic-line",
    packSize: "1 kg",
    intensity: 5,
    price: 420000,
    image: "/images/lines/classic-line/linea-classica-decaffeinato.jpg",
    description: {
      uz: "Kofeinsiz — ta'mi to'liq saqlangan.",
      ru: "Без кофеина — с полностью сохранённым вкусом.",
      en: "Decaffeinated — with the flavour fully preserved.",
    },
  },
  {
    id: "so-brazil",
    name: "Single Origin Brazil",
    category: "beans",
    collection: "single-origin",
    packSize: "1 kg",
    intensity: 6,
    price: 500000,
    image: "/images/lines/single-origin/brazil.png",
    description: {
      uz: "Brasil — Braziliya qahvachiligining yuragi, mashhur Alta Mogiana mintaqasidan yagona kelib chiqishli 100% arabika; Santos donlarining yarim nam ishlovi ajoyib sifat beradi. Slow Roasting usulidagi o'rtacha qovurish kakao, yong'oq, qovurilgan don va yangi non notalari bilan zich, o'rab oluvchi ta'mni ochadi; yakun shirin va uzoq, qamish shakari tusi bilan. Juda zich, moyli tana va deyarli nol nordonlik bu qahvani har qanday auditoriya uchun tushunarli va yoqimli qiladi. Intensivlik 6/10, tana 7/10, xushbo'ylik 9/10. Espresso, kapuchino va latte uchun ideal; specialty kofexonalar, restoranlar va mehmonxonalarga tavsiya etiladi.",
      ru: "Brasil — 100% арабика единственного происхождения из знаменитого региона Alta Mogiana, сердца бразильского кофеводства, где полувлажная обработка зёрен Santos даёт исключительное качество. Средняя обжарка Slow Roasting раскрывает плотный, обволакивающий вкус с нотами какао, орехов, поджаренных злаков и свежего хлеба; финиш сладкий и долгий, с оттенком тростникового сахара. Очень плотное маслянистое тело и почти нулевая кислотность делают этот кофе понятным и приятным для любой аудитории. Интенсивность 6/10, тело 7/10, аромат 9/10. Идеален для эспрессо, капучино и латте; рекомендован specialty-кофейням, ресторанам и отелям.",
      en: "Brasil is a 100% single-origin Arabica from the famous Alta Mogiana region, the heart of Brazilian coffee growing, where semi-washed Santos beans deliver exceptional quality. Medium slow roasting reveals a dense, enveloping taste with notes of cocoa, nuts, toasted cereals and fresh bread; the finish is sweet and long with a touch of cane sugar. A very dense, buttery body and almost no acidity make this coffee easy and pleasant for any audience. Intensity 6/10, body 7/10, aroma 9/10. Ideal for espresso, cappuccino and latte; recommended for specialty cafés, restaurants and hotels.",
    },
  },
  {
    id: "so-colombia",
    name: "Single Origin Colombia",
    category: "beans",
    collection: "single-origin",
    packSize: "1 kg",
    intensity: 4,
    price: 290000,
    image: "/images/lines/single-origin/colombia.png",
    description: {
      uz: "Colombia — Kolumbiyaning baland tog' mintaqalaridan (Uila, Narino va Kauka), dunyoning eng murakkab va e'tirof etilgan terruarlaridan biridan yagona kelib chiqishli 100% arabika. Supremo navi donlari qo'lda teriladi va yuvilgan ishlovdan o'tadi — shundan ta'mning ajoyib tozaligi. Slow Roasting usulidagi o'rtacha qovurish yorqin, murakkab profilni ochadi: karamel, sut shokoladi, qizil rezavorlar, jigarrang shakar va bodom, jonli muvozanatli nordonlik va nafis o'rtacha tana bilan. Yakun uzoq, shirin-mevali, nozik sitrus notalari bilan. Intensivlik 4/10, tana 6/10, xushbo'ylik 9/10. Espresso, purover va filtr uchun ideal; specialty kofexonalar, fine dining restoranlar va mehmonxonalarga tavsiya etiladi.",
      ru: "Colombia — 100% арабика единственного происхождения из высокогорных регионов Колумбии (Уила, Нариньо и Каука), одного из самых сложных и признанных терруаров мира. Зёрна сорта Supremo собираются вручную и проходят мытую обработку — отсюда исключительная чистота вкуса. Средняя обжарка Slow Roasting раскрывает яркий комплексный профиль: карамель, молочный шоколад, красные ягоды, коричневый сахар и миндаль с живой сбалансированной кислотностью и элегантным средним телом. Финиш долгий, сладковато-фруктовый, с тонкими цитрусовыми нотами. Интенсивность 4/10, тело 6/10, аромат 9/10. Идеален для эспрессо, пуровера и фильтра; рекомендован specialty-кофейням, ресторанам fine dining и отелям.",
      en: "Colombia is a 100% single-origin Arabica from the country's high-altitude regions (Huila, Nariño and Cauca), one of the most complex and celebrated terroirs in the world. Supremo-grade beans are hand-picked and washed, hence the exceptional clarity of taste. Medium slow roasting reveals a bright, complex profile of caramel, milk chocolate, red berries, brown sugar and almond, with lively, balanced acidity and an elegant medium body. The finish is long and sweet-fruity with fine citrus notes. Intensity 4/10, body 6/10, aroma 9/10. Ideal for espresso, pour-over and filter; recommended for specialty cafés, fine-dining restaurants and hotels.",
    },
  },
  {
    id: "so-honduras",
    name: "Single Origin Honduras",
    category: "beans",
    collection: "single-origin",
    packSize: "1 kg",
    intensity: 5,
    price: 290000,
    image: "/images/lines/single-origin/honduras.png",
    description: {
      uz: "Honduras — Gonduras baland tog' mintaqalaridan (Montesillos, Opalaka, Kopan, Komayagua, Agalta) yagona kelib chiqishli 100% arabika; SHG toifasidagi donlar uchun ideal sharoit. Qo'lda terish va yuvilgan ishlov profilning ajoyib tozaligi va shaffofligini beradi. Slow Roasting usulidagi o'rtacha qovurish sut shokoladi, o'rmon yong'og'i, karamel va tropik meva notalari, jonli nordonlik va yumaloq o'rtacha tana bilan yorqin, muvozanatli ta'mni ochadi. Yakun toza, shirin, vanil va sitrus tuslari bilan — nafisligi va muvozanati bilan maftun etuvchi qahva. Intensivlik 5/10, tana 6/10, xushbo'ylik 8/10. Espresso, purover va filtr uchun ideal; specialty kofexonalar, restoranlar va mehmonxonalarga tavsiya etiladi.",
      ru: "Honduras — 100% арабика единственного происхождения из высокогорных регионов Гондураса (Монтесильос, Опалака, Копан, Комаягуа, Агальта) с идеальными условиями для зёрен класса SHG. Ручной сбор и мытая обработка дают исключительную чистоту и прозрачность профиля. Средняя обжарка Slow Roasting раскрывает яркий сбалансированный вкус с нотами молочного шоколада, лесного ореха, карамели и тропических фруктов, живой кислотностью и округлым средним телом. Финиш чистый, сладковатый, с оттенками ванили и цитруса — кофе, покоряющий элегантностью и балансом. Интенсивность 5/10, тело 6/10, аромат 8/10. Идеален для эспрессо, пуровера и фильтра; рекомендован specialty-кофейням, ресторанам и отелям.",
      en: "Honduras is a 100% single-origin Arabica from the country's high-altitude regions (Montecillos, Opalaca, Copán, Comayagua, Agalta), ideal conditions for SHG-grade beans. Hand-picking and washed processing give exceptional clarity and transparency of flavour. Medium slow roasting reveals a bright, balanced cup with notes of milk chocolate, hazelnut, caramel and tropical fruit, lively acidity and a round medium body. The finish is clean and sweet with hints of vanilla and citrus — a coffee that wins with elegance and balance. Intensity 5/10, body 6/10, aroma 8/10. Ideal for espresso, pour-over and filter; recommended for specialty cafés, restaurants and hotels.",
    },
  },
  {
    id: "beans-antica-bottega-500",
    name: "Antica Bottega",
    category: "beans",
    collection: "caffe-in-grani",
    packSize: "500 g",
    intensity: 5,
    price: 230000,
    image: "/products/shop/caffe-grani__anticabottega-500g.png",
    description: {
      uz: "Shirin va nozik aralashma — 500 g qadoqda.",
      ru: "Сладкая деликатная смесь — упаковка 500 г.",
      en: "The sweet, delicate blend — 500 g pack.",
    },
  },
  {
    id: "beans-espresso-500",
    name: "Espresso",
    category: "beans",
    collection: "caffe-in-grani",
    packSize: "500 g",
    intensity: 7,
    price: 190000,
    image: "/products/shop/caffe-grani__espresso-500g.png",
    description: {
      uz: "To'liq tanali espresso aralashmasi — 500 g.",
      ru: "Полнотелая эспрессо-смесь — 500 г.",
      en: "Full-bodied espresso blend — 500 g.",
    },
  },
  {
    id: "beans-granaroma-500",
    name: "Granaroma",
    category: "beans",
    collection: "caffe-in-grani",
    packSize: "500 g",
    intensity: 8,
    price: 195000,
    image: "/products/shop/caffe-grani__granaroma-500g.png",
    description: {
      uz: "Shokoladli klassik aralashma — 500 g.",
      ru: "Шоколадная классическая смесь — 500 г.",
      en: "The chocolaty classic blend — 500 g.",
    },
  },
  {
    id: "beans-arabica-bio",
    name: "Arabica Bio",
    category: "beans",
    collection: "caffe-in-grani",
    packSize: "1 kg",
    intensity: 6,
    price: 460000,
    image: "/products/shop/caffe-grani__sacco-bio-1kg.png",
    description: {
      uz: "Organik sertifikatli 100% Arabica donalari.",
      ru: "Органическая 100% арабика в зёрнах.",
      en: "Certified organic 100% Arabica beans.",
    },
  },
  {
    id: "beans-wic-honduras",
    name: "Women in Coffee — Honduras Blend",
    category: "beans",
    collection: "caffe-in-grani",
    packSize: "250 g",
    intensity: 6,
    price: 140000,
    image: "/products/shop/caffe-grani__grani-wic-honduras-blend-250g.png",
    description: {
      uz: "Women in Coffee loyihasi — Gonduras ayol fermerlari yetishtirgan qahva.",
      ru: "Проект Women in Coffee — кофе, выращенный женщинами-фермерами Гондураса.",
      en: "Women in Coffee project — coffee grown by women farmers in Honduras.",
    },
  },
  {
    id: "ground-arabica-tin-moka",
    name: "100% Arabica Lattina (Moka)",
    category: "ground",
    collection: "caffe-macinato",
    packSize: "250 g tin",
    intensity: 6,
    price: 150000,
    image: "/products/shop/caffe-macinato__lattina-caffe-macinato-100-arabica-250g.png",
    description: {
      uz: "Moka uchun maydalangan 100% Arabica — afsonaviy bankada.",
      ru: "100% арабика помола для моки — в легендарной банке.",
      en: "100% Arabica ground for moka — in the iconic tin.",
    },
  },
  {
    id: "ground-decaf-tin",
    name: "Decaffeinato Lattina",
    category: "ground",
    collection: "caffe-macinato",
    packSize: "250 g tin",
    intensity: 5,
    price: 150000,
    image: "/products/shop/caffe-macinato__lattina-decaffeinato-250g.png",
    description: {
      uz: "Kofeinsiz, moka uchun maydalangan — bankada.",
      ru: "Декаф помола для моки — в банке.",
      en: "Decaf ground for moka — in the tin.",
    },
  },
  {
    id: "ground-montagna-tin",
    name: "Montagna 100% Arabica Lattina",
    category: "ground",
    collection: "caffe-macinato",
    packSize: "250 g tin",
    intensity: 6,
    price: 160000,
    image: "/products/shop/caffe-macinato__lattina-montagna-100-arabica.png",
    description: {
      uz: "Baland tog' plantatsiyalaridan 100% Arabica.",
      ru: "100% арабика с высокогорных плантаций.",
      en: "100% Arabica from high-mountain plantations.",
    },
  },
  {
    id: "ground-granaroma-500",
    name: "Granaroma Macinato",
    category: "ground",
    collection: "caffe-macinato",
    packSize: "2 × 250 g",
    intensity: 7,
    price: 180000,
    image: "/products/shop/caffe-macinato__caffe-macinato-gran-aroma-2x250g.png",
    description: {
      uz: "Granaroma moka uchun — 2 × 250 g.",
      ru: "Granaroma для моки — 2 × 250 г.",
      en: "Granaroma for moka — 2 × 250 g.",
    },
  },
  {
    id: "ground-granaroma-1kg",
    name: "Granaroma Macinato",
    category: "ground",
    collection: "caffe-macinato",
    packSize: "4 × 250 g",
    intensity: 7,
    price: 340000,
    image: "/products/shop/caffe-macinato__caffe-macinato-gran-aroma-4x250g.png",
    description: {
      uz: "Granaroma moka uchun — 4 × 250 g tejamkor to'plam.",
      ru: "Granaroma для моки — выгодный набор 4 × 250 г.",
      en: "Granaroma for moka — value pack of 4 × 250 g.",
    },
  },
  {
    id: "ground-antica-bottega-500",
    name: "Antica Bottega Macinato",
    category: "ground",
    collection: "caffe-macinato",
    packSize: "2 × 250 g",
    intensity: 4,
    price: 210000,
    image: "/products/shop/caffe-macinato__caffe-macinato-antica-bottega-2x250g.png",
    description: {
      uz: "Yumshoq Antica Bottega moka uchun — 2 × 250 g.",
      ru: "Мягкая Antica Bottega для моки — 2 × 250 г.",
      en: "Smooth Antica Bottega for moka — 2 × 250 g.",
    },
  },
  {
    id: "ground-vergnano-ce",
    name: "Vergnano C'è",
    category: "ground",
    collection: "caffe-macinato",
    packSize: "250 g",
    intensity: 7,
    price: 95000,
    image: "/products/shop/caffe-macinato__vergnano-ce-250g.png",
    description: {
      uz: "Kundalik moka uchun klassik aralashma.",
      ru: "Классическая смесь для ежедневной моки.",
      en: "The classic everyday moka blend.",
    },
  },
  {
    id: "ground-wic-tin",
    name: "Women in Coffee Lattina",
    category: "ground",
    collection: "caffe-macinato",
    packSize: "250 g tin",
    intensity: 6,
    price: 160000,
    image: "/products/shop/caffe-macinato__lattina-wic-250g.png",
    description: {
      uz: "Women in Coffee — bankada maydalangan qahva.",
      ru: "Women in Coffee — молотый кофе в банке.",
      en: "Women in Coffee — ground coffee in the tin.",
    },
  },
  {
    id: "pink-tin-bianca",
    name: "Lattina Women in Coffee — Pennika Bianca",
    category: "ground",
    collection: "pink-collection",
    packSize: "250 g tin",
    intensity: 6,
    price: 180000,
    image: "/products/shop/pink-collection__lattina-wic-pennika-bianca.png",
    description: {
      uz: "Rassom Pennika dizaynidagi oq banka — Women in Coffee qahvasi.",
      ru: "Белая банка с дизайном художницы Pennika — кофе Women in Coffee.",
      en: "White tin with artwork by Pennika — Women in Coffee coffee.",
    },
  },
  {
    id: "pink-tin-rosa",
    name: "Lattina Women in Coffee — Pennika Rosa",
    category: "ground",
    collection: "pink-collection",
    packSize: "250 g tin",
    intensity: 6,
    price: 180000,
    image: "/products/shop/pink-collection__lattina-wic-pennika-rosa.png",
    description: {
      uz: "Rassom Pennika dizaynidagi pushti banka — Women in Coffee qahvasi.",
      ru: "Розовая банка с дизайном художницы Pennika — кофе Women in Coffee.",
      en: "Pink tin with artwork by Pennika — Women in Coffee coffee.",
    },
  },
  {
    id: "pink-mug",
    name: "Mug Women in Coffee",
    category: "accessories",
    collection: "pink-collection",
    packSize: "1 pc",
    intensity: null,
    price: 120000,
    image: "/products/shop/pink-collection__mug-per-women-in-coffee.png",
    description: {
      uz: "Women in Coffee loyihasining krujkasi.",
      ru: "Кружка проекта Women in Coffee.",
      en: "The Women in Coffee project mug.",
    },
  },
  {
    id: "pink-keep-cup",
    name: "Keep Cup Women in Coffee",
    category: "accessories",
    collection: "pink-collection",
    packSize: "1 pc",
    intensity: null,
    price: 150000,
    image: "/products/shop/pink-collection__keep-cup-wic.png",
    description: {
      uz: "Qayta ishlatiladigan Women in Coffee stakani — yo'lda qahva uchun.",
      ru: "Многоразовый стакан Women in Coffee — для кофе в дороге.",
      en: "Reusable Women in Coffee cup — for coffee on the go.",
    },
  },
  {
    id: "pink-tshirt",
    name: "T-Shirt Women in Coffee",
    category: "accessories",
    collection: "pink-collection",
    packSize: "M / L / XL",
    intensity: null,
    price: 190000,
    image: "/products/shop/pink-collection__t-shirt-wic-tg-m.png",
    description: {
      uz: "Women in Coffee futbolkasi.",
      ru: "Футболка Women in Coffee.",
      en: "Women in Coffee T-shirt.",
    },
  },
  {
    id: "pink-notebook-giallo",
    name: "Quaderno by Pennika — Giallo",
    category: "accessories",
    collection: "pink-collection",
    packSize: "1 pc",
    intensity: null,
    price: 60000,
    image: "/products/shop/pink-collection__quaderno-by-pennika-giallo.png",
    description: {
      uz: "Pennika dizaynidagi daftar — sariq.",
      ru: "Блокнот с дизайном Pennika — жёлтый.",
      en: "Notebook designed by Pennika — yellow.",
    },
  },
  {
    id: "pink-notebook-rosa",
    name: "Quaderno by Pennika — Rosa",
    category: "accessories",
    collection: "pink-collection",
    packSize: "1 pc",
    intensity: null,
    price: 60000,
    image: "/products/shop/pink-collection__quaderno-by-pennika-rosa.png",
    description: {
      uz: "Pennika dizaynidagi daftar — pushti.",
      ru: "Блокнот с дизайном Pennika — розовый.",
      en: "Notebook designed by Pennika — pink.",
    },
  },
  {
    id: "pink-notebook-viola",
    name: "Quaderno by Pennika — Viola",
    category: "accessories",
    collection: "pink-collection",
    packSize: "1 pc",
    intensity: null,
    price: 60000,
    image: "/products/shop/pink-collection__quaderno-by-pennika-viola.png",
    description: {
      uz: "Pennika dizaynidagi daftar — binafsha.",
      ru: "Блокнот с дизайном Pennika — фиолетовый.",
      en: "Notebook designed by Pennika — purple.",
    },
  },
  {
    id: "pink-notebook-bundle",
    name: "Bundle 3 quaderni Pennika",
    category: "accessories",
    collection: "pink-collection",
    packSize: "3 pcs",
    intensity: null,
    price: 160000,
    image: "/products/shop/pink-collection__bundle-3-quaderni-pennika.png",
    description: {
      uz: "Pennika dizaynidagi uchta daftar to'plami.",
      ru: "Набор из трёх блокнотов Pennika.",
      en: "Set of three Pennika notebooks.",
    },
  },
  {
    id: "pink-book",
    name: "Il fuoco sotto al caffè (EN)",
    category: "accessories",
    collection: "pink-collection",
    packSize: "Book",
    intensity: null,
    price: 220000,
    image: "/products/shop/pink-collection__il-fuoco-sotto-al-caffe-ed-inglese.png",
    description: {
      uz: "Caffè Vergnano tarixi haqidagi kitob — ingliz tilida.",
      ru: "Книга об истории Caffè Vergnano — на английском.",
      en: "The book on Caffè Vergnano's story — English edition.",
    },
  },
];

export const categories: Category[] = [
  "beans",
  "ground",
  "capsules",
  "pods",
  "accessories",
];

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("ru-RU").format(price);
}
